# This is a basic workflow to help you get started with Actions

name: NugetPackage RandomMareano

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      CSPROJ: ./RandomMareanoLibrary/RandomMareanoLibrary.csproj
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - name: Geração do package
        run: dotnet pack ${{ env.CSPROJ }} -c Release -o out
        
      - name: Push no NuGet
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path:  out/RandomMareanoLibrary.1.0.0.nupkg
          repo-owner:  MauricioMatsu
          gh-user:  'MauricioMatsu'
          token:  ${{ secrets.GITHUB_TOKEN }}
        
